// SQDC Products Data - Generated 2025-10-04T00:55:21.810Z
// This is a fallback data source when products.json cannot be fetched

window.PRODUCTS_DATA = [
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "820939006337",
    "name": "Afghan Kush",
    "brand": "Promenade",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 20,
    "thcMax": 25,
    "manualThc": "20",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628693095723",
    "name": "Alien Kush AAA",
    "brand": "Le Malin Vert",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628518001090",
    "name": "Avignon",
    "brand": "R'Belle",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "620376135450",
    "name": "Banana Baby",
    "brand": "Bud Lafleur",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "17",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "620376135375",
    "name": "Banana Daddy",
    "brand": "Bud Lafleur",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628518000413",
    "name": "Bastille",
    "brand": "R'Belle",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "688318000860",
    "name": "BC Bubba Pink Biologique",
    "brand": "Simply Bare",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628308901210",
    "name": "BC Fire OG Biologique",
    "brand": "Simply Bare",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 27,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628308901029",
    "name": "BC Frosted Fruit Cake Bio",
    "brand": "Simply Bare",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "671148101081",
    "name": "Black Cherry Punch",
    "brand": "Wô Là",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628123510734",
    "name": "Brise Fruitée",
    "brand": "Bouket",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628124835430",
    "name": "Bubble Up",
    "brand": "Tribal",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "800129904636",
    "name": "Ça Sent l'Gaz",
    "brand": "OMY",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 18,
    "thcMax": 24,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "688083012259",
    "name": "CBD OG Kush",
    "brand": "Vert",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 3,
    "thcMax": 9,
    "manualThc": "4",
    "manualCbd": "12"
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628011959126",
    "name": "Chem Cookies #44",
    "brand": "Cheers Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "688318001591",
    "name": "Comatose",
    "brand": "1964",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "990017000547",
    "name": "Cool Aid Kush",
    "brand": "Bold",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628634099254",
    "name": "Dans le Divan",
    "brand": "T'es Dans L'Champ",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 20,
    "thcMax": 25,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "836780002749",
    "name": "Exotic Gas",
    "brand": "The Loud Plug",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "666592001025",
    "name": "Fire Breath",
    "brand": "Back Forty",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628124835027",
    "name": "Gelato Mint",
    "brand": "Tribal",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 20,
    "thcMax": 28,
    "manualThc": "22",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "824165002132",
    "name": "Grand Daddy Purps",
    "brand": "Good Supply",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628634303184",
    "name": "H26 Indica",
    "brand": "Bleuh",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628634303115",
    "name": "H30 Kush",
    "brand": "Blakh",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "875429000678",
    "name": "Herbes de Province",
    "brand": "Fleurons",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628011959485",
    "name": "Holy Kush",
    "brand": "Saint-Laurent Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "820939007150",
    "name": "Honeysuckle Kush",
    "brand": "Tam Tams",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "870857000788",
    "name": "Iced Kush",
    "brand": "TerreBud",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628634303603",
    "name": "Indic'once",
    "brand": "Bleuh",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "814559000615",
    "name": "Inspérimental",
    "brand": "Terroir",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "820939006306",
    "name": "Island Pink Kush",
    "brand": "Pure Laine",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "800129900010",
    "name": "Kush Cookies",
    "brand": "OMY",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "878865000578",
    "name": "Kush Life",
    "brand": "Carmel Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "814559000592",
    "name": "Kush Tard",
    "brand": "Terroir",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "834407001076",
    "name": "LA WoMac",
    "brand": "BLKMKT",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "697238114229",
    "name": "Lagune",
    "brand": "Hexo",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "620376128056",
    "name": "Lava Cake",
    "brand": "Bud Lafleur",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628693095440",
    "name": "Le P'tit Phéno Indica",
    "brand": "Pecko",
    "format": "1 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628719632024",
    "name": "Mac Deluxe",
    "brand": "Sumo",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "990312073376",
    "name": "Meat Breath",
    "brand": "Hatrick",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628124835072",
    "name": "Meat Pie",
    "brand": "Nugz",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 20,
    "thcMax": 25,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "800129900041",
    "name": "Mélange Indica",
    "brand": "OMY",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "875429000395",
    "name": "Menu Cantine",
    "brand": "Fleurons",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628308905195",
    "name": "OG Kush",
    "brand": "1964",
    "format": "1 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628719126981",
    "name": "Panier Fruité",
    "brand": "Blee Fleurs",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628942597640",
    "name": "Papaya Bomb",
    "brand": "Sumo",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "820939001622",
    "name": "Pine Tar Kush",
    "brand": "Promenade",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628582000357",
    "name": "Pink Kush",
    "brand": "San Rafael '71",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 19,
    "thcMax": 25,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628069580334",
    "name": "Pink Panties",
    "brand": "Pistol and Paris",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "870814001056",
    "name": "Pure Kush",
    "brand": "QcGoldtech",
    "format": "1 g",
    "formatCategory": "flower",
    "thcMin": 20,
    "thcMax": 27,
    "manualThc": "20",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628425320192",
    "name": "Pure Michigan",
    "brand": "Sheeesh",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "688083014550",
    "name": "Purple Mint Cake",
    "brand": "Maitri",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 19,
    "thcMax": 25,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628176417035",
    "name": "Root Beer Float",
    "brand": "Bold",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628518002240",
    "name": "Saint-Laurent",
    "brand": "R'Belle",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "841432010584",
    "name": "Spinach GMO Cookies",
    "brand": "Spinach",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628582003310",
    "name": "Stink Biscuit",
    "brand": "San Raf",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "820939002476",
    "name": "Sugar Cookies",
    "brand": "Promenade",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 29,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "824165002590",
    "name": "Sweet Berry Kush",
    "brand": "Good Supply",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628719632147",
    "name": "Tropical Splash",
    "brand": "Sumo",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "878865009250",
    "name": "Zebra Stripes",
    "brand": "Carmel Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628069580303",
    "name": "ZeddyZ",
    "brand": "Cannafrogs",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 30,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "671148601482",
    "name": "Amnesia OG",
    "brand": "Big Bag O' Buds",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 18,
    "thcMax": 22,
    "manualThc": "20",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "827763000272",
    "name": "Amsterdam Sativa",
    "brand": "Highly Dutch Organic",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "671148904118",
    "name": "Apples & Cream",
    "brand": "Trailblazer",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 4,
    "thcMax": 11,
    "manualThc": "5",
    "manualCbd": "8"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634099131",
    "name": "Aweille Réveille",
    "brand": "T'es Dans L'Champ",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "688318004431",
    "name": "BC Fruit Loopz Biologique",
    "brand": "Simply Bare",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939002483",
    "name": "Berry Cream Puff",
    "brand": "Promenade",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 29,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "688318000273",
    "name": "Bleu Nuit",
    "brand": "1964",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 16,
    "thcMax": 24,
    "manualThc": "22",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939006252",
    "name": "Blood Orange",
    "brand": "Tam Tams",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634090107",
    "name": "Blueberry Yum Yum",
    "brand": "5 Points Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939004135",
    "name": "Citrus Tsunami",
    "brand": "Homage",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "843087002440",
    "name": "Dark Shadow Haze",
    "brand": "Clair De Lune",
    "format": "1 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628124828012",
    "name": "Early Lemon Berry",
    "brand": "Nugz",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 21,
    "thcMax": 29,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634303191",
    "name": "H26 Sativa",
    "brand": "Bleuh",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634303146",
    "name": "H30 Haze",
    "brand": "Blakh",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "620376135603",
    "name": "Hollywood",
    "brand": "Bud Lafleur",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "694144007218",
    "name": "Jean Guy",
    "brand": "Good Supply",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "824165002118",
    "name": "Jean Guy",
    "brand": "Good Supply",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628518000451",
    "name": "Jungl' Cake",
    "brand": "MTL Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628242702621",
    "name": "Jungle Fumes",
    "brand": "Figr",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "666592000899",
    "name": "L'Bon Voisin",
    "brand": "Fleurs de Lise",
    "format": "1 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "666592000042",
    "name": "La Cerise sur le Funday",
    "brand": "Fleurs de Lise",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "666592000097",
    "name": "La Cerise sur le Funday",
    "brand": "Fleurs de Lise",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "814559000684",
    "name": "La Sournoise",
    "brand": "Terroir",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628693095464",
    "name": "Le P'tit Phéno CBD",
    "brand": "Pecko",
    "format": "1 g",
    "formatCategory": "flower",
    "thcMin": 6,
    "thcMax": 12,
    "manualThc": "7",
    "manualCbd": "10"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "697238124303",
    "name": "Lemon Haze",
    "brand": "Hexo",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 21,
    "thcMax": 28,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "688083017247",
    "name": "Lemon Meringue Pie",
    "brand": "Tweed",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628120090192",
    "name": "Lemon Pepper Punch",
    "brand": "Green Joy",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "694144000219",
    "name": "Libérer",
    "brand": "Solei",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 2,
    "manualThc": "0",
    "manualCbd": "16"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628120090734",
    "name": "Mango Cheese",
    "brand": "Green Joy",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 8,
    "thcMax": 14,
    "manualThc": "10",
    "manualCbd": "17"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "870857002171",
    "name": "Mango Fuel",
    "brand": "Clem et Co",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "627987031621",
    "name": "Mango K",
    "brand": "Kokotte",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628518000130",
    "name": "Marseille",
    "brand": "R'Belle",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "875429000401",
    "name": "Menu Dessert",
    "brand": "Fleurons",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 21,
    "thcMax": 29,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628124815036",
    "name": "Nugz Sativa",
    "brand": "Nugz",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "697238112287",
    "name": "OS.130",
    "brand": "Original Stash",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 29,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "838729000083",
    "name": "Painted Lady",
    "brand": "Pure Trichomes x Velada",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 3,
    "manualThc": "0",
    "manualCbd": "8"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "814559000714",
    "name": "Painted Lady",
    "brand": "Terroir",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 6,
    "manualThc": "0",
    "manualCbd": "12"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939005408",
    "name": "Pineapple OG",
    "brand": "Pure Laine",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "627987928211",
    "name": "Rêve Lucide",
    "brand": "Nueva+",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 1,
    "manualThc": "0",
    "manualCbd": "13"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "838728000435",
    "name": "Rose Gold Pavé",
    "brand": "Uncommon Cannabis Co.",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939006221",
    "name": "Sour Tangie",
    "brand": "Promenade",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 18,
    "thcMax": 22,
    "manualThc": "18",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "841432010867",
    "name": "Spinach Lemon Skunk",
    "brand": "Spinach",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "814559000738",
    "name": "Star d'un Soir",
    "brand": "Terroir",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "620376135146",
    "name": "Strawberry Bubbles",
    "brand": "Bud Lafleur",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939006283",
    "name": "Strawberry Cough",
    "brand": "Promenade",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939006900",
    "name": "Strawberry Lemonade",
    "brand": "Homage",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628582003198",
    "name": "Strawberry Sensi",
    "brand": "San Rafael '71",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628693095044",
    "name": "Super Lemon Haze Biologique",
    "brand": "Wio",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 4,
    "thcMax": 10,
    "manualThc": "7",
    "manualCbd": "11"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628582000524",
    "name": "Tangerine Dream",
    "brand": "San Rafael '71",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 11,
    "thcMax": 18,
    "manualThc": "16",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "870857000122",
    "name": "Time Wreck",
    "brand": "XoPro",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628693095433",
    "name": "Top Cola AAAA",
    "brand": "Wio",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "671148011144",
    "name": "Ultra Jean-G",
    "brand": "Wô Là",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628176622811",
    "name": "Apricot Cream and Cheese 1:1",
    "brand": "Clem et Co",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 7,
    "thcMax": 15,
    "manualThc": "9",
    "manualCbd": "14"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628942229350",
    "name": "Beau Dimanche",
    "brand": "Nueva+",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 14,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "666592000912",
    "name": "Ben Trop",
    "brand": "Fleurs de Lise",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 18,
    "thcMax": 22,
    "manualThc": "18",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628634303214",
    "name": "Blanh Hybride",
    "brand": "Blanh",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 21,
    "thcMax": 29,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628634099582",
    "name": "Ça Varie CBD",
    "brand": "T'es Dans L'Champ",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 3,
    "manualThc": "0",
    "manualCbd": "18"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "820939002599",
    "name": "Cannatonic",
    "brand": "Promenade",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 1,
    "manualThc": "1",
    "manualCbd": "18"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628124835065",
    "name": "CBD Runtz",
    "brand": "Orchid",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 5,
    "thcMax": 13,
    "manualThc": "12",
    "manualCbd": "9"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "827763004287",
    "name": "Céréale à la Mode",
    "brand": "Cookies",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "841432040031",
    "name": "Cotton Candy",
    "brand": "Sonique",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "870857000002",
    "name": "Coup de Foudre",
    "brand": "XoPro",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628124835058",
    "name": "Cuban Linx",
    "brand": "Tribal",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 22,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "875429001200",
    "name": "Découverte",
    "brand": "Be Humble.",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628693095358",
    "name": "Fruity Pebbles OG",
    "brand": "Vertical 7",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "870857000870",
    "name": "Gary Payton",
    "brand": "Grail",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628069580013",
    "name": "Gelato 33",
    "brand": "Lot 420",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "843087004208",
    "name": "GG",
    "brand": "Clair De Lune",
    "format": "1 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628123510024",
    "name": "Goofiez",
    "brand": "Celebrity",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628120090079",
    "name": "Grape Yogurt",
    "brand": "Green Joy",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628634099407",
    "name": "Grasse Matinée",
    "brand": "T'es Dans L'Champ",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 3,
    "manualThc": "0",
    "manualCbd": "18"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "820939001066",
    "name": "Gros Plaisirs",
    "brand": "Pure Laine Cannabis",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "820939002254",
    "name": "Harlequin 1:1",
    "brand": "Promenade",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 6,
    "thcMax": 12,
    "manualThc": "9",
    "manualCbd": "9"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "814559000646",
    "name": "Hybride 101",
    "brand": "Terroir",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 10,
    "thcMax": 16,
    "manualThc": "14",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628942530906",
    "name": "Juste CBD",
    "brand": "Cannabiomedic",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 0,
    "thcMax": 2,
    "manualThc": "0",
    "manualCbd": "12"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628634303481",
    "name": "Kik Cola",
    "brand": "Goldh",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 27,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "666592000882",
    "name": "L' Joe Louis",
    "brand": "Fleurs de Lise",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "688083013775",
    "name": "L'Entre Deux",
    "brand": "Vert",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 7,
    "thcMax": 13,
    "manualThc": "9",
    "manualCbd": "13"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628176622804",
    "name": "Lab 101",
    "brand": "Clem et Co",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 7,
    "thcMax": 15,
    "manualThc": "9",
    "manualCbd": "14"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628090610406",
    "name": "LCP",
    "brand": "Cultures Chloris",
    "format": "15 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628693095372",
    "name": "Long Valley Legend",
    "brand": "Ostara",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 6,
    "thcMax": 12,
    "manualThc": "8",
    "manualCbd": "10"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "627987544411",
    "name": "Mint Chocolate Chip Biologique",
    "brand": "Sweetgrass Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628124835447",
    "name": "Neon Sunshine",
    "brand": "Tribal",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628069580044",
    "name": "Orange Cake",
    "brand": "Lot 420",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628069580648",
    "name": "Orange Creamsicle",
    "brand": "Cannafrogs",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "820939001684",
    "name": "Pennywise 1:1",
    "brand": "Promenade",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 6,
    "thcMax": 12,
    "manualThc": "8",
    "manualCbd": "7"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "824165002156",
    "name": "Pineapple Express",
    "brand": "Good Supply",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 19,
    "thcMax": 25,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "824164005011",
    "name": "Pineapple Upside Down CKE",
    "brand": "Palmetto",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628011959454",
    "name": "Pomelo Soda",
    "brand": "Cheers Cannabis",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 10,
    "thcMax": 16,
    "manualThc": "16",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628176622200",
    "name": "Purple Mountain Majesty",
    "brand": "Endo",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 8,
    "thcMax": 13,
    "manualThc": "10",
    "manualCbd": "8"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628942876455",
    "name": "Red Velvet Ice Cream",
    "brand": "Seaweed",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 29,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "800129904254",
    "name": "Royal Mauiberry",
    "brand": "OMY",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 10,
    "thcMax": 16,
    "manualThc": "14",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628090610154",
    "name": "RRW",
    "brand": "Cultures Chloris",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "820939002452",
    "name": "Sac Banane",
    "brand": "Promenade",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 20,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "688083015717",
    "name": "Scout 91K",
    "brand": "Vert",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 7,
    "thcMax": 13,
    "manualThc": "9",
    "manualCbd": "11"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "814559000585",
    "name": "Soir de Semaine",
    "brand": "Terroir",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "870857000467",
    "name": "Super Top Gun",
    "brand": "TerreBud",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628693095389",
    "name": "SuperBoof",
    "brand": "Vertical 7",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "820939002247",
    "name": "Symphonie",
    "brand": "Tam Tams",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "688083002595",
    "name": "Twd. Balanced",
    "brand": "Twd.",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 4,
    "thcMax": 11,
    "manualThc": "6",
    "manualCbd": "6"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "824165004570",
    "name": "Very Berry",
    "brand": "Good Supply",
    "format": "28 g",
    "formatCategory": "flower",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "870857001396",
    "name": "Zénitude",
    "brand": "Herbe et Co",
    "format": "3,5 g",
    "formatCategory": "flower",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "824165003696",
    "name": "Animal Rntz Redees Hemp'd",
    "brand": "Redecan",
    "format": "10 unités de 0,4 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "620376111386",
    "name": "Banana Daddy",
    "brand": "Bud Lafleur",
    "format": "1 unité de 1 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "620376155076",
    "name": "Banana Daddy",
    "brand": "Bud Lafleur",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": "0"
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628518000420",
    "name": "Bastille",
    "brand": "R'Belle",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "671148301177",
    "name": "Bête de Diesel",
    "brand": "Shred",
    "format": "14 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 26,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "841432042073",
    "name": "Blue Monster",
    "brand": "Sonique",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628176223414",
    "name": "Blueberry Muffin",
    "brand": "Irony",
    "format": "2 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 22,
    "thcMax": 29,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628124825349",
    "name": "Bubble Up",
    "brand": "Tribal",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "688083012518",
    "name": "CBD OG Kush",
    "brand": "Vert",
    "format": "10 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 2,
    "thcMax": 8,
    "manualThc": "4",
    "manualCbd": "13"
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628693095426",
    "name": "Death Bubba Biologique",
    "brand": "Pecko",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628634303580",
    "name": "Drette Indica",
    "brand": "Bleuh",
    "format": "9 unités de 0,45 g",
    "formatCategory": "preroll",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628124825011",
    "name": "Gelato Mint",
    "brand": "Tribal",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 28,
    "manualThc": "22",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628011959409",
    "name": "Holy Kush",
    "brand": "Saint-Laurent Cannabis",
    "format": "5 unités de 0,4 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "820939007174",
    "name": "Honeysuckle Kush",
    "brand": "Tam Tams",
    "format": "1 unité de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "878865000585",
    "name": "Kush Life",
    "brand": "Carmel Cannabis",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "834407001625",
    "name": "LA WoMac",
    "brand": "BLKMKT",
    "format": "1 unité de 1 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "875429000425",
    "name": "Méchant Pétard",
    "brand": "Fleurons",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 28,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628124810598",
    "name": "Nugz Wrap Indica",
    "brand": "Nugz",
    "format": "1 unité de 1 g",
    "formatCategory": "preroll",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "835339000168",
    "name": "Ono Planet of the grapes",
    "brand": "Ono Cannabis",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628176223292",
    "name": "Pillage de Trésors",
    "brand": "Irony",
    "format": "28 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 19,
    "thcMax": 25,
    "manualThc": "20",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "820939004715",
    "name": "Pink God",
    "brand": "Promenade",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 18,
    "thcMax": 25,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628582001729",
    "name": "Pink Kush",
    "brand": "San Rafael '71",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 19,
    "thcMax": 25,
    "manualThc": "21",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "990311700167",
    "name": "Pink Kush Balancé",
    "brand": "5 Points Cannabis",
    "format": "5 unités de 0,3 g",
    "formatCategory": "preroll",
    "thcMin": 8,
    "thcMax": 14,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "824164005882",
    "name": "Rockstar",
    "brand": "Bon Jak",
    "format": "10 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 13,
    "thcMax": 18,
    "manualThc": "16",
    "manualCbd": ""
  },
  {
    "type": "Indica",
    "typeIcon": "F01",
    "store": "77074",
    "sku": "628518001724",
    "name": "Wes' Coast Kush",
    "brand": "MTL Cannabis",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "878865008871",
    "name": "Animal Face",
    "brand": "Carmel Cannabis",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628942229398",
    "name": "Banane Plantée",
    "brand": "Nueva+",
    "format": "2 unités de 1 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634303344",
    "name": "Blanh Sativa",
    "brand": "Blanh",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 21,
    "thcMax": 29,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "688318000822",
    "name": "Bleu Nuit",
    "brand": "1964",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 18,
    "thcMax": 24,
    "manualThc": "19",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939003107",
    "name": "Blue Dream",
    "brand": "Promenade",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 15,
    "thcMax": 22,
    "manualThc": "19",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628176223155",
    "name": "Candyland",
    "brand": "Irony",
    "format": "14 unités de 0,25 g",
    "formatCategory": "preroll",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "671148601048",
    "name": "Citrique Électrique",
    "brand": "Shred",
    "format": "14 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 26,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "824165003177",
    "name": "Cold Creek Kush Redees Hemp'd",
    "brand": "Redecan",
    "format": "20 unités de 0,4 g",
    "formatCategory": "preroll",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634303320",
    "name": "Colorado Cherry",
    "brand": "Bleuh Light",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 0,
    "thcMax": 4,
    "manualThc": "0",
    "manualCbd": "17"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628124884018",
    "name": "Early Lemon Berry",
    "brand": "Nugz",
    "format": "14 unités de 0,6 g",
    "formatCategory": "preroll",
    "thcMin": 21,
    "thcMax": 29,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "826966013287",
    "name": "Explosion de Fruits",
    "brand": "Canaca",
    "format": "10 unités de 0,33 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 28,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628693095655",
    "name": "Frozen Lemon Biologique",
    "brand": "Wio",
    "format": "10 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "843087001689",
    "name": "Goliat",
    "brand": "Weed Me",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634303092",
    "name": "H27 Sativa",
    "brand": "Grindh",
    "format": "14 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "688083014161",
    "name": "Jack Haze",
    "brand": "7ACRES",
    "format": "2 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 17,
    "thcMax": 23,
    "manualThc": "20",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "694144002770",
    "name": "Jean Guy",
    "brand": "Good Supply",
    "format": "1 unité de 1 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 27,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "694144007690",
    "name": "Jean Guy",
    "brand": "Good Supply",
    "format": "7 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 20,
    "thcMax": 27,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "666592000370",
    "name": "La Cerise sur le Funday",
    "brand": "Fleurs de Lise",
    "format": "6 unités de 0,6 g",
    "formatCategory": "preroll",
    "thcMin": 22,
    "thcMax": 29,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628942229312",
    "name": "La Copine",
    "brand": "Nueva+",
    "format": "14 unités de 1 g",
    "formatCategory": "preroll",
    "thcMin": 7,
    "thcMax": 12,
    "manualThc": "8",
    "manualCbd": "10"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "627987928150",
    "name": "Le Fameux",
    "brand": "Nueva+",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "666592000776",
    "name": "Le Passe Partout",
    "brand": "Fleurs de Lise",
    "format": "10 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628120090697",
    "name": "Lemon Pepper Punch",
    "brand": "Green Joy",
    "format": "2 unités de 1 g",
    "formatCategory": "preroll",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "990017000516",
    "name": "Lemon Sour Diesel",
    "brand": "Bold",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628120090727",
    "name": "Mango Cheese",
    "brand": "Green Joy",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 8,
    "thcMax": 14,
    "manualThc": "10",
    "manualCbd": "17"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628124810604",
    "name": "Nugz Wrap Sativa",
    "brand": "Nugz",
    "format": "1 unité de 1 g",
    "formatCategory": "preroll",
    "thcMin": 22,
    "thcMax": 28,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939005439",
    "name": "Pineapple OG",
    "brand": "Pure Laine",
    "format": "2 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "26",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "824165003658",
    "name": "Purple Churro Classique",
    "brand": "Redecan",
    "format": "10 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 26,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628693095815",
    "name": "Purple Gushrs LSO",
    "brand": "Vertical 7",
    "format": "15 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628634099759",
    "name": "Purple Haze",
    "brand": "5 Points Cannabis",
    "format": "7 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628942229459",
    "name": "Rêve Lucide",
    "brand": "Nueva+",
    "format": "2 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 0,
    "thcMax": 1,
    "manualThc": "0",
    "manualCbd": "14"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "629108249144",
    "name": "Sativa Js",
    "brand": "Daily Special",
    "format": "7 unités de 0,3 g",
    "formatCategory": "preroll",
    "thcMin": 18,
    "thcMax": 24,
    "manualThc": "19",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "870857000726",
    "name": "Sativa X30",
    "brand": "514",
    "format": "30 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 23,
    "thcMax": 30,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "838729000243",
    "name": "Skunkcussion",
    "brand": "Pure Trichomes",
    "format": "10 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 21,
    "thcMax": 27,
    "manualThc": "21",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "820939003558",
    "name": "Special Haze",
    "brand": "Pure Laine Cannabis",
    "format": "5 unités de 0,33 g",
    "formatCategory": "preroll",
    "thcMin": 21,
    "thcMax": 29,
    "manualThc": "25",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628518000482",
    "name": "Strawberry N' Mintz",
    "brand": "MTL Cannabis",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628693095242",
    "name": "Super Lemon Haze Biologique",
    "brand": "Wio",
    "format": "8 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 5,
    "thcMax": 13,
    "manualThc": "7",
    "manualCbd": "11"
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "628582001736",
    "name": "Tangerine Dream",
    "brand": "San Rafael '71",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 9,
    "thcMax": 15,
    "manualThc": "12",
    "manualCbd": ""
  },
  {
    "type": "Sativa",
    "typeIcon": "F02",
    "store": "77074",
    "sku": "671148012011",
    "name": "Ultra Sour",
    "brand": "Wô Là",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 18,
    "thcMax": 25,
    "manualThc": "23",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628176622828",
    "name": "Apricot Cream and Cheese 1:1",
    "brand": "Clem et Co",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 7,
    "thcMax": 15,
    "manualThc": "11",
    "manualCbd": "15"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "820939001240",
    "name": "Artisans",
    "brand": "DLYS",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 18,
    "thcMax": 29,
    "manualThc": "27",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628176223353",
    "name": "Brise de Plume",
    "brand": "Feather Weight",
    "format": "10 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 14,
    "thcMax": 19,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628124825059",
    "name": "CBD Runtz",
    "brand": "Orchid",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 5,
    "thcMax": 13,
    "manualThc": "12",
    "manualCbd": "9"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "627987928167",
    "name": "Complice",
    "brand": "Nueva+",
    "format": "2 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 10,
    "thcMax": 16,
    "manualThc": "10",
    "manualCbd": "9"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "870857002119",
    "name": "Coup de Foudre",
    "brand": "XoPro",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 12,
    "thcMax": 18,
    "manualThc": "",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628124825042",
    "name": "Cuban Linx",
    "brand": "Tribal",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 22,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": "0"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628634090268",
    "name": "Grasse Matinée",
    "brand": "T'es Dans L'Champ",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 0,
    "thcMax": 3,
    "manualThc": "0",
    "manualCbd": "16"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628090610529",
    "name": "LCP",
    "brand": "Cultures Chloris",
    "format": "4 unités de 0,75 g",
    "formatCategory": "preroll",
    "thcMin": 25,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628242801249",
    "name": "Mango Haze",
    "brand": "Color Cannabis",
    "format": "2 unités de 0,35 g",
    "formatCategory": "preroll",
    "thcMin": 4,
    "thcMax": 11,
    "manualThc": "7",
    "manualCbd": "7"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "620376111119",
    "name": "Moby Dick",
    "brand": "Bud Lafleur",
    "format": "1 unité de 1 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628124825356",
    "name": "Neon Sunshine",
    "brand": "Tribal",
    "format": "5 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "29",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "800129905312",
    "name": "Skunk Muffinz",
    "brand": "OMY",
    "format": "2 unités de 1 g",
    "formatCategory": "preroll",
    "thcMin": 23,
    "thcMax": 29,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628693377171",
    "name": "Slush P",
    "brand": "Sheeesh",
    "format": "7 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "24",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "671148302150",
    "name": "Toute Garnie",
    "brand": "Shred Tubes",
    "format": "70 unités de 0,4 g",
    "formatCategory": "preroll",
    "thcMin": 18,
    "thcMax": 22,
    "manualThc": "19",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628693377157",
    "name": "Trop Juice",
    "brand": "Sheeesh",
    "format": "7 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 24,
    "thcMax": 30,
    "manualThc": "28",
    "manualCbd": ""
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "688083006463",
    "name": "Twd. Balanced",
    "brand": "Twd.",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 4,
    "thcMax": 12,
    "manualThc": "8",
    "manualCbd": "7"
  },
  {
    "type": "Hybride",
    "typeIcon": "F03",
    "store": "77074",
    "sku": "628693377256",
    "name": "Velvet Punch Haze",
    "brand": "Groupe SûrNaturel",
    "format": "3 unités de 0,5 g",
    "formatCategory": "preroll",
    "thcMin": 25,
    "thcMax": 29,
    "manualThc": "29",
    "manualCbd": ""
  }
];
